srcApplicationAddEdit As screen:

    recHeaderApplicationAddEdit As rectangle:
        Fill: =RGBA(153, 207, 236, 1)
        Width: =1366
        ZIndex: =1

    lblTitleApplicationAddEdit As label:
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =Bold
        Height: =100
        Size: =32
        Text: ="Central Application Management"
        Width: =740
        X: =92
        ZIndex: =2

    lftMenuApplicationAddEdit As LeftMenu:
        Height: =668
        MenuBgColor: =RGBA(179, 179, 179, 1)
        MenuColor: =RGBA(255, 255, 255, 1)
        MenuItems: |-
            =Table(
                    {
                        MenuLabel: "Applications",
                        MenuIcon: Icon.Controller,
                        MenuScreenNavigate: srcApplicationSearch,
                        MenuID: 1
                    },
                    {
                        MenuLabel: "Categorys",
                        MenuIcon: Icon.Tag,
                        MenuScreenNavigate: srcCategorySearch,
                        MenuID: 2
                    },
                    {
                        MenuLabel: "Users",
                        MenuIcon: Icon.Person,
                        MenuScreenNavigate: srcUsersSearch,
                        MenuID: 3
                    },
                    {
                        MenuLabel: "User Privs",
                        MenuIcon: Icon.Lock,
                        MenuScreenNavigate: srcCategorySearch,
                        MenuID: 4
                    },
                    {
                        MenuLabel: "Priv Request",
                        MenuIcon: Icon.Mail,
                        MenuScreenNavigate: srcRequestSearch,
                        MenuID: 5
                    }
                )
        Width: =317
        Y: =100
        ZIndex: =3

    icoBackApplicationAddEdit As icon.BackArrow:
        Color: =RGBA(255, 255, 255, 1)
        Icon: =Icon.BackArrow
        OnSelect: =Back()
        X: =13
        Y: =13
        ZIndex: =4

    recSeparatorTitleApplicationAddEdit As rectangle:
        Fill: =RGBA(128, 128, 128, 1)
        Height: =1
        Width: =1049
        X: =317
        Y: =181
        ZIndex: =5

    lblCatalogTitleApplicationAddEdit As label:
        Align: =Center
        Color: =RGBA(128, 128, 128, 1)
        FontWeight: =FontWeight.Bold
        Height: =81
        Size: =28
        Text: =If(frmApplication.Mode = FormMode.Edit, "Edit Application", "Create Application")
        Width: =1049
        X: =317
        Y: =100
        ZIndex: =6

    imgUserAddEdit As image:
        BorderColor: =RGBA(128, 128, 128, 1)
        BorderThickness: =1
        DisabledBorderColor: =RGBA(255, 255, 255, 1)
        Height: =77
        Image: ='kisspng-computer-icons-user-profile-info-5acde51ebdcc36.0919547315234429747774'
        RadiusBottomLeft: =imgUserAddEdit.Height
        RadiusBottomRight: =imgUserAddEdit.Height
        RadiusTopLeft: =imgUserAddEdit.Height
        RadiusTopRight: =imgUserAddEdit.Height
        Width: =80
        X: =1246
        Y: =13
        ZIndex: =7

    lblUserApplicationAddEdit As label:
        Align: =Right
        Color: =RGBA(255, 255, 255, 1)
        Height: =36
        Size: =20
        Text: |-
            ="User: Oscar Morales Martinez"
        Width: =395
        X: =832
        Y: =13
        ZIndex: =8

    lblRolApplicationAddEdit As label:
        Align: =Right
        Color: =RGBA(255, 255, 255, 1)
        Height: =36
        Size: =20
        Text: |-
            ="Role: Admin"
        Width: =395
        X: =832
        Y: =54
        ZIndex: =9

    frmApplication As form:
        DataSource: =APPLICATIONS
        Height: =467
        Item: =_application
        OnSuccess: =Navigate(srcApplicationSearch, ScreenTransition.Fade)
        Width: =1032
        X: =325
        Y: =192
        ZIndex: =10

        ID_CATEGORY_DataCard2 As typedDataCard.numberEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="ID_CATEGORY"
            Default: =ThisItem.ID_CATEGORY
            DisplayMode: =Parent.DisplayMode
            DisplayName: ="ID_CATEGORY"
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            Required: =false
            Update: =Value(ddlCategories.Selected.ID)
            Width: =frmApplication.Width
            X: =1
            Y: =1
            ZIndex: =1

            DataCardKey2 As label:
                AutoHeight: =true
                Height: =34
                Size: =18
                Text: ="Category"
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            ErrorMessage2 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =ddlCategories.Y + ddlCategories.Height
                ZIndex: =3

            StarVisible2 As label:
                Align: =Align.Center
                Height: =DataCardKey2.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey2.Y
                ZIndex: =4

            ddlCategories As dropdown:
                Default: =LookUp (CATEGORIES, ID = Parent.Default).DESCRIPTION
                Height: =55
                Items: =CATEGORIES
                Width: =975
                X: =27
                Y: =53
                ZIndex: =5

        APPLICATION_CODE_DataCard2 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="APPLICATION_CODE"
            Default: =ThisItem.APPLICATION_CODE
            DisplayMode: =Parent.DisplayMode
            DisplayName: ="APPLICATION_CODE"
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@APPLICATIONS], DataSourceInfo.MaxLength, "APPLICATION_CODE")
            Required: =true
            Update: =DataCardValue4.Text
            Width: =frmApplication.Width
            X: =0
            Y: =0
            ZIndex: =11

            DataCardKey4 As label:
                AutoHeight: =true
                Height: =34
                Size: =18
                Text: ="Application Code"
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue4 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                Height: =60
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey4.Y + DataCardKey4.Height + 5
                ZIndex: =2

            ErrorMessage4 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue4.Y + DataCardValue4.Height
                ZIndex: =3

            StarVisible4 As label:
                Align: =Align.Center
                Height: =DataCardKey4.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey4.Y
                ZIndex: =4

        APPLICATION_NAME_DataCard2 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="APPLICATION_NAME"
            Default: =ThisItem.APPLICATION_NAME
            DisplayMode: =Parent.DisplayMode
            DisplayName: ="APPLICATION_NAME"
            Fill: =RGBA(0, 0, 0, 0)
            Height: =69
            MaxLength: =DataSourceInfo([@APPLICATIONS], DataSourceInfo.MaxLength, "APPLICATION_NAME")
            Required: =true
            Update: =DataCardValue5.Text
            Width: =frmApplication.Width
            X: =0
            Y: =1
            ZIndex: =11

            DataCardKey5 As label:
                AutoHeight: =true
                Height: =34
                Size: =18
                Text: ="Application Name"
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue5 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                Height: =60
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey5.Y + DataCardKey5.Height + 5
                ZIndex: =2

            ErrorMessage5 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue5.Y + DataCardValue5.Height
                ZIndex: =3

            StarVisible5 As label:
                Align: =Align.Center
                Height: =DataCardKey5.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey5.Y
                ZIndex: =4

    btnSaveApplication As button:
        Fill: =RGBA(153, 207, 236, 1)
        Height: =txtApplicationNameSearch.Height
        HoverFill: =ColorFade(RGBA(153, 207, 236, 1), -20%)
        OnSelect: =SubmitForm(frmApplication)
        Text: =If(frmApplication.Mode = FormMode.Edit, "Edit", "Save")
        Width: =176
        X: =656
        Y: =688
        ZIndex: =11

    btnBackToListApplication As button:
        Fill: =RGBA(116, 116, 116, 1)
        Height: =txtApplicationNameSearch.Height
        HoverFill: =ColorFade(RGBA(153, 207, 236, 1), -20%)
        OnSelect: =Navigate(srcApplicationSearch, ScreenTransition.Fade)
        Text: ="Back to List"
        Width: =176
        X: =886
        Y: =688
        ZIndex: =12

